### ISSUE TITLE
Logging in as a new user doesn't logout the old user.

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#17]
I just saw something that is very concerning from a user management perspective.  This likely is an issue with DocumentCloud, but I'm reporting it here in case I'm wrong.

When I login as a user, if I don't logout, then when I try logging in as a second user, I'm in the system as the first.

Steps to reproduce:

1. Go to the main page
2. Login as user1
3. Close the browser tab or entirely close the browser
4. Go back to the main page
5. Login as user2

After login as user2, the current user will show as user1.

Expected action:

1. Going to the login page acts as a logout and the second login will end up with user2 logged in.
2. Pressing the login button acts as a logout for user1, and will end up with user2 logged in.

**Comment by wsloand** [comment]
Perhaps a simple fix for this is to cause any activity on the http site to be redirected to https.

**Comment by roberttdev** [comment]
DC base finally fixed this issue, and that is what they did.

**Comment by roberttdev** [comment]
I've set the Prod/QA sites to always re-route to HTTPS, so hopefully that should solve the problem.

**Comment by wsloand** [comment]
Works for me.
