### ISSUE TITLE
Allow Two Documents to be Claimed at a Time

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#59]
While writing the training documentation, I realized that I need to encourage asking questions.  Allowing a user to work on two documents at once, will allow the user to wait on the answer to a question rather than wanting to continue to power through the work incorrectly.

Can you please allow a user to claim more than one document at a time?  I have a slight preference that they can claim two documents total (in any task, DE, QC, QA, SuppDE), but if it is much simpler that they can claim two documents per task that they are qualified for, that is perfectly OK.

**Comment by roberttdev** [comment]
I haven't written the permissions for File Upload users yet, so it is unrelated.

**Comment by wsloand** [comment]
This looks good (not 100% tested, but tested with two user types).
