### ISSUE TITLE
Upload Users can Delete Documents

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#65]
An upload user (upload1) can delete a document.  Only admin should be able to delete.

Can you please disable that ability and remove "Delete" from the menu that shows up when right clicking on the document on the login page?  Also, remove "Delete" from buttons at the bottom of the edit window (when clicking the pencil icon to the right of the document name).

Please also apply these changes to all groups but admin.

**Comment by billdenney** [comment]
Looks good.

**Comment by wsloand** [comment]
Looks good.
