### ISSUE TITLE
Double Clicking Cloning Should Clone the Cloned-from Value

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#75]
Often when cloning a data structure, we desire to clone many of the original values, too.

Current steps to get desired result:
1. Clone a group
2. Navigate to the data point to clone
3. Click the clone icon
4. Find and click on the existing data point in the document view

I'd like to replace step 4 with "click the clone icon again" to clone from the original point.

**Comment by roberttdev** [comment]
Double-clicking the icon will be non-obvious for DE users who aren't explicitly trained on it (or who forget).  Should we add a new icon for cloning from the copied value, that shows up only for cloned points?

**Comment by wsloand** [comment]
That's a good point that people will accidentally double click on it and not know what happened.

How about: clicking on the clone icon pops up two text choices on a drop-down menu.  Choice 1: "Clone a data point" which works the way that clone currently works.  Choice 2: "Clone the data point that this came from" which will select the data point with the same annotation title from within the originally-cloned-from group.

If the group is not cloned, Choice 2 would be grayed out, and if the user clicks Choice 2 while it is grayed out, a notification would pop up saying "This group was not cloned, so we cannot locate the point automatically.  Please clone the point by clicking 'Clone a data point' and selecting the right point in the document view."

**Comment by roberttdev** [comment]
I can do it this way, but it seems like a lot of extra clicks for users, which could slow down data entry.  I think we can fit another icon in the space we have, that only shows up on cloned points, to reduce both copy mechanisms to one click -- the tradeoff being that it's not as much instructive text.  Up to you.

**Comment by wsloand** [comment]
After some user focus grouping, this feature can go away.  I thought it would be useful, but cloning is complex enough for users without adding another method.

I'll close the issue when I'm back in front of a computer.
