### ISSUE TITLE
When QA Rejects a Point, Approve All should Gray Out

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#77]
When QA rejects a point, the approve all button is still available.  When clicked, the button doesn't appear to do anything, but visually, it is still clickable.

Steps:
1. Login as QA
2. Reject a point (and enter a note)
3. Preferred automatic action: "Approve All" button text becomes gray and nonresponsive to click.

**Comment by roberttdev** [comment]
Currently, if there is a rejected point, the system just approves all the non-rejected points.  Do you want to remove this functionality in favor of what you described here, so there is no shortcut if the user wants to reject one point and then approve the rest in one fell swoop?

**Comment by wsloand** [comment]
Nope, it's good as is now that I understand it better.
