### ISSUE TITLE
Zooming All the Way in Stretches the Image

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#80]
When zooming all the way in, the html image size is 1400 px wide, but the actual image is only 967 px wide.  It would be nice to have the largest zoom size the same as the largest image size.  Perhaps the image would get compressed at lower zooms, but it should not be stretched at the highest zoom.

Also, I would be potentially interested in looking at pngs instead of gifs (my reading online has suggested that sizes may be smaller with .png files, but it's not definitive since it's dependent on color depth).

**Comment by roberttdev** [comment]
Are you thinking the image should be generated @ 1400px, or the largest zoom should be dropped to 967px?

**Comment by wsloand** [comment]
I'm going for image at 1400.

**Comment by wsloand** [comment]
I just uploaded document number 69, and the largest image size appears to be 1000 px wide, and it's still stretched to 1400px.  Can you look into increasing the native image width to 1400px?

**Comment by roberttdev** [comment]
I think there are core properties of the document that limit the max size -- it's set to attempt 1400 if possible, but in my testing, different documents came up at different max widths.  Does the same thing happen when you try to generate the images manually?

**Comment by wsloand** [comment]
I won't be able to test it for a few days, but I think that the issue may be that it is fitting into a 1400px box.  So, the long axis is 1400px when I'd like the short axis to be 1400px.

An alternate to trying to specify the short axis dimensions (usually hard) could be to fit it in an 1800px box.  That way, letter and A4 PDFs will have an approximately 1400px short edge.

**Comment by wsloand** [comment]
I finally got to test this, and the following command (which seems to mirror closely to the DocSplit command format) gives me what I'd like (a ~1400px short edge):

gm convert +adjoin -define pdf:use-cropbox=true -density 150 -resize 1800x1800 nihms513647.pdf[0] nihms513647-0.gif

The output pdf is 1391x1800.

I think that the pixel sizes just need to match more closely to the scaling up of an 8.5x11 inch page to the zooms.  Looking at what each of the zoom levels give us, I think we'll want the following for each zoom level to be covered by its own image

normal: 906x906 px (to get a 700px wide image)
large: 1812x1812 px (to get a 1400px wide image)

**Comment by roberttdev** [comment]
Fixed.  I advise not going back and re-adjusting the image size of already annotated docs, as the annotation location is correlated to the size of the image, and it may result it old annotations being off.

**Comment by wsloand** [comment]
I just uploaded document 70, and it was created with a large image that is still 1000x1310px.

**Comment by roberttdev** [comment]
Try again.. I needed to both make a tweak to the S3 storage logic and reboot the entire server, as the old logic was cached in separate processes.

**Comment by wsloand** [comment]
I just uploaded document 81, and it is 1000px by 1415px

**Comment by roberttdev** [comment]
I can't see document 81 with admin, but I just uploaded 82 ("FinanceReregulationFactSheetFINAL"), and it's 1400x1812 on the highest zoom.  Are you sure you're on the highest zoom, and are you looking at the  URL for the actual image?  It saves two, a 700px-wide and a 1400px-wide.

On a side note, it appears there's something busted with the file listing/search that's hiding these docs that I need to look into.

**Comment by wsloand** [comment]
Sorry, I accidentally deleted doc 80.  No bug on that part.  I'll try another upload tonight.

**Comment by wsloand** [comment]
I just uploaded document 84 (test.pdf).  The "normal" image (test-p1-normal.gif) is 700x990px.  The "large" image (test-p1-large.gif) is 1000x1415px.  I was expecting the large one to be 1280x1812px.

**Comment by roberttdev** [comment]
That is indeed the wrong size.  I just uploaded 85 (June2), which is formatted correctly.  Either something on your computer is affecting the process, or (more likely) the file itself that you're using to test has a property that limits the size which its image can be expanded to.

You can test the latter by attempting to generate the images with graphicsmagick on the command line, and seeing if they are also limited.  If they are not, email me the specific PDF you're using, and I'll see what happens when I try and upload it.

**Comment by roberttdev** [comment]
I added 'density' of 300 to the request, and that brings it up to 1281x1812 (keep in mind we set it at 1812x1812 instead of 1800x1800).  The only other thing different from your command is that we pass 'rolling' as 'true', so see if that affects things.

To test, make sure there are NO other copies of that PDF uploaded to the system, as the document image splitter can identify identical documents and will just point to those images instead as a time-saving measure.  This is likely part of the problem we saw before.  So you will either need to delete all copies of that PDF from prod, or test in an empty QA environment.

**Comment by wsloand** [comment]
That sounds good.  When you say "no other copies", does that mean by filename or by file contents?  If by filename, that could be a problem in the future because I can easily imagine uncontrolled filenames causing a conflict.

**Comment by roberttdev** [comment]
I didn't look deep into how it determines a match, but it seems to be content-based, not filename-based (maybe a unique hash based on the file contents).  A different doc with the same name will not trigger it, but the same doc with a different name will.

**Comment by wsloand** [comment]
This appears to have been fixed a while ago.
