### ISSUE TITLE
Cannot Open SuppDE Document

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#87]
Both admin and DE users cannot open SuppDE documents.  When an admin user tries to access a document marked as ready for SuppDE, a 403 error is thrown.  DE users cannot see the documents in their document list.

**Comment by roberttdev** [comment]
That's because it's already claimed by someone.. the admin can see it, but not claim it, and it doesn't appear to other DE's at all.  The admin view says it's claimed by "Louise Bittick".

**Comment by wsloand** [comment]
Yup, not a bug.
