### ISSUE TITLE
Template Aliases

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#89]
To simplify DE, I realized that it would help to remove the distinction between Group names and Template names.  In other words, it would be nice if I could tell the DE user "Result" is for a result measurement; "Demographic" is for a demographic measurement; ...  Then they would not need to enter both the template name and the group name.

Here is the general process that I'm thinking of:

1. Maintain both the group template and group name fields.
2. The user can choose the group template or group name fields or both.
3. If a group name is entered, it is used as the group name.
4. If the user enters a group template without a group name, then the group template is used as the group name by default.
5. If both are entered, the group name is used as the group name (i.e. the same as 3 above, but being explicit).

WIthin group templates, we would need a template alias field.  The template alias would allow the same template to be presented to the user as a template

**Comment by roberttdev** [comment]
Would this problem be solved by simply placing the template name into the Group Name field when a template is selected?  The user can choose to edit at their discretion, but by default they can just continue from there with the template name as the group name by default.

**Comment by wsloand** [comment]
Automatically placing the template name in the group name would solve half of the issue.  The other half is that if like to be able to use aliases for the template name (where that alias would be copied to the group name, too).

As I think about it a bit more, I think that we don't need the alias part; the above paragraph will do everything needed.

**Comment by roberttdev** [comment]
Fixed

**Comment by wsloand** [comment]
Looks good
