### ISSUE TITLE
Refresh the Document List When a Document is Closed

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#90]
When a document tab is closed, refresh the document list in the main tab.  It is understood that if a document tab is opened independent of the document list tab, refresh won't be possible.

Steps desired:
1. Login (tab 1)
2. Double click to open a document on tab 1
3. Tab 2 opens with the document contents (page view, data tree, etc.)
4. Work in tab 2.
5. Close tab 2 (in any way: perhaps complete work, perhaps save work, perhaps just close the tab, or any other way)

Result:
Automatic refresh of tab 1 so that the current state of all documents shows up instead of the state when tab 2 was opened.

**Comment by roberttdev** [comment]
Fix added.  Separate fix for Drop, DE Complete, QC Complete, QC Reject, and QA Complete.  Also added refresh on document view initialize to reflect the claim.  The system can only push a refresh request on user-initiated status changes in the app interface.. if the user simply closes the tab using "X" or whatnot in the browser, that will not refresh the opening page.  Looked into handling edge cases, and it looks like we can't without getting in-depth with a Chrome plugin that must be installed on every user's browser.

**Comment by wsloand** [comment]
This looks good.
