### ISSUE TITLE
Allow User Deletion if They Have Not Contributed

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#92]
Disabling a user currently says "{firstname} {lastname} will not be able to log in to DocumentCloud. Public documents and annotations provided by admin10 adminlast10 will remain available. Contact support  to completely purge admin10 adminlast10's account."

If the user has not contributed anything, can the option be "Delete" instead of "Disable"?

If the user has contributed something, what is the right path?

**Comment by roberttdev** [comment]
We can do that, but we have to proactively check all over the system for footprints of the user to confirm that they indeed have not done anything that might be orphaned if they're removed.  As functionality grows, the odds that our check isn't thorough enough grows as well.

We're probably safer by sticking with Disable, but if it will result in a lot of clutter on the Account screen, perhaps we should introduce some UI enhancements to separate disabled accounts from active ones?

**Comment by wsloand** [comment]
That's fair.  We can set it to sort by account type later.

This is very low priority.

**Comment by wsloand** [comment]
As I think about this one more, it makes sense that it would be an intensive operation with low benefit (as you described).  I'm closing this.
