### ISSUE TITLE
When Account is Re-Enabled, the Role Shows as Contributor

### ISSUE THREAD

**Issue by wsloand** [roberttdev/dactyl4#93]
See title.

Steps to reproduce:

1. Create an account
  * Login
  * Click the "Accounts" tab
  * Click the DACTYL project on the left
  * Click "+ New Account"
  * Give a first name, last name, email address, and role
  * Click "OK"
2. Click the edit pencil next to their name.
3. Click the "disable" button
4. Click the "disable" button
  * Role shows as "(Disabled)"
5. Click the edit pencil next to their name
6. Click "re-enable"

Expected result:
The role shows as the original role.

Result:
The role shows "Contributor".

**Comment by wsloand** [comment]
Secondary to this.  When I go back in (log out and log back in, then go to the accounts), the role doesn't show up.  This is a bigger issue

**Comment by wsloand** [comment]
The account creation email link then works and I now have an account that I can't see on the account list page.

**Comment by roberttdev** [comment]
Fixed

**Comment by wsloand** [comment]
Looks good
